### ISSUE TITLE
how to show the history with the datetime when this line executed?

### ISSUE THREAD

**Issue by liudonglei** [jupyter/jupyter_console#109]
just like the history cmd output format in ubuntu ? such as this 
  896  16-10-03 16:57:53 cd /etc/apache2
  897  16-10-03 16:57:54 ll
  898  16-10-03 16:57:58 cat dav_svn_my.passwd 
  899  16-10-03 16:58:54 ll
  900  16-10-03 16:58:58 ll ~
  901  16-10-03 17:03:00 exit
  902  16-10-12 15:50:11 history 

when I use the magic commend  in Jupyter Qt console  not show the time 
147/1: import pyzmq
147/2: import pyzmq
I think show the date time maybe user-friendly

**Comment by takluyver** [comment]
The IPython history database does not record a timestamp for each command. It does store a timestamp for the start and end of each session, but I don't think we expose any functionality to see them.

**Comment by liudonglei** [comment]
Thank you very much for your answer.

**Comment by alphaCTzo7G** [comment]
It would be very helpful to debug tricky situations, if `ipython`/`jupyter-console` saved the timestamps like `zsh` does.

**Comment by alphaCTzo7G** [comment]
seems like there is a way.. have to try this one out: https://github.com/ipython/ipython/wiki/Cookbook:-Dated-logging

**Comment by alphaCTzo7G** [comment]
First use `%hist -o -g -f ipython_history.md` to output the history (input and output) to a text file. (http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-history)

Then you can use the the `get_session_info` function to retreive the date and time the session you are interested (http://ipython.readthedocs.io/en/stable/api/generated/IPython.core.history.html?highlight=hist#IPython.core.history.HistoryAccessor.get_session_info)

    profile_hist=IPython.core.history.HistoryAccessor(profile='default')
    profile_hist.get_session_info(100)

This will print out something like 

    (100, datetime.datetime(2018, 2, 13, 19, 8, 30, 40691), None, None, '')

**Comment by liudonglei** [comment]
Thank you very much for your answer, alphaCTzo7G 
I will try your method.
