### ISSUE TITLE
console does not send is_complete_requests?

### ISSUE THREAD

**Issue by stevengj** [jupyter/jupyter_console#11]
I was implementing the latest protocol in JuliaLang/IJulia.jl#325, and I wanted to test out my handling of the `is_complete_request` message.  However, the `console` front-end does not seem to send this message to check whether inputs are complete; it just sends an `execute_request` whenever you hit `<enter>`.

**Comment by minrk** [comment]
@stevengj qtconsole uses is_complete_request now. It's a bit trickier to make that change here, since this one is a subclass of TerminalInteractiveShell, which relies heavily on InputSplitter. Hopefully the coming move to prompt toolkit from readline will make it easier to make this fix.

**Comment by stevengj** [comment]
Thanks @minrk, I appreciate your efforts.  I don't use the console or qtconsole myself except for testing of features like this, but I recall that the console was quite useful when we were first bootstrapping IJulia, so I'm glad to see that it is still moving forward.

**Comment by dsblank** [comment]
Is there any work-around for forcing another line of input to be allowed (without changing the syntax)? For example, if shift+enter allowed the user to go to the next line, that would be helpful. (working on an assembly language kernel).

**Comment by minrk** [comment]
I don't think we can have alternate behavior for modifier+enter with readline.

**Comment by dsblank** [comment]
I have found a work-around:

```nasm
; This is the start of my ASM program (
.ORIG x3000
    LEA R0, HELLO
    PUTS
    HALT
HELLO .STRINGZ "Hello, World!"
.END
; This is the end )
```

That is, put a open/close parens at the end of lines which has a comment-to-end-of-line character before it.

**Comment by dsblank** [comment]
My workaround no longer works for Jupyter 4. Note that this also applies to just ENTER. I can't use these languages in jupyter_console any more.
