### ISSUE TITLE
quit from attached kernel with keep_kernel=True at console when Ctrl-\ is pressed

### ISSUE THREAD

**Issue by lebedov** [jupyter/jupyter_console#126]
In the past, it was possible to exit an ipython console instance connected to a running kernel without terminating the latter by pressing Ctrl-. With ipython 5.3.0, jupyter-console 5.1.0, and ipykernel 4.6.1 (used with Python 2.7.13), this no longer appears to be the case; I have to manually run quit(keep_kernel=True), and Ctrl-\ doesn't have any effect. Does the console frontend catch SIGQUIT? If so, is there some way to enable the old behavior (either programatically or via a config option)?

**Comment by takluyver** [comment]
We're not catching SIGQUIT, but I think that prompt_toolkit puts the terminal into a mode where Ctrl-\ is not automatically translated to a signal. We can probably handle it as a shortcut ourselves and implement similar behaviour.

**Comment by takluyver** [comment]
#130 adds Ctrl-\ as a shortcut.

**Comment by lebedov** [comment]
👍
