### ISSUE TITLE
matplotlibrc ignored by design?

### ISSUE THREAD

**Issue by damca** [jupyter/jupyter_console#131]
It would seem that importing `matplotlib` should execute the `~/.matplotlib/matplotlibrc` (for which I have made the default backend `Qt5Agg`).

In IPython:
```bash
❯ ipython   
                                                                                                                                                                                         
In [1]: import matplotlib.pyplot as plt

In [2]: plt.get_backend()
Out[2]: 'Qt5Agg'
```

However,

```bash
❯ jupyter console   
                                                                                                                                                                                         
In [1]: import matplotlib.pyplot as plt

In [2]: plt.get_backend()
Out[2]: 'module://ipykernel.pylab.backend_inline'
```

First, is this behavior by design, if so, why? Second, is there a way I can configure `~/.jupyter/jupyter_console_config.py` to respect the `~/.matplotlib/matplotlibrc`?

This is with IPython 6.1.0 and Jupyter console 5.1.0

**Comment by takluyver** [comment]
It is loading the matplotlibrc file, but the kernel uses the `MPLBACKEND` environment variable to set the inline backend, which takes priority over the config file. If you want to override that, you can set `MPLBACKEND` before starting Jupyter, or call `%matplotlib qt5`, or `mpl.use('qt5agg')` before importing pyplot.

**Comment by damca** [comment]
I didn't know about the `MPLBACKEND` environment variable. Works great, thanks!
