### ISSUE TITLE
multiline magic command doesn't end (Jupyter console)

### ISSUE THREAD

**Issue by DataBranner** [jupyter/jupyter_console#139]
In a Jupyter notebook, a "cell magic" command (prefixed with two percent signs) ends at the end of the cell and is automatically invoked:

[![%%timeit in Jupyter notebook][1]][1]

But if I try the same thing in the Jupyter console, the command never ends, after any number of blank lines:

[![%%timeit in Jupyter console][2]][2]

That only happens if I invoke IPython as `jupyter console`, though. If I invoke IPython directly as `ipython`, the cell magic command completes after one blank line:

[![%%timeit in ipython console][3]][3]

For each example, the versions of Python and IPython are identical: Python 3.5.2 and IPython 6.1.0 on one machine (installed with pip), Python 3.4.5 and IPython 5.1.0 on another (installed with Conda).

  [1]: https://i.stack.imgur.com/Mha5I.png
  [2]: https://i.stack.imgur.com/hCYq3.png
  [3]: https://i.stack.imgur.com/UQQW3.png

**Comment by Carreau** [comment]
Thanks !

Cross linking [SO question](https://stackoverflow.com/questions/46157789/jupyter-ending-multiline-magic-command-in-console/46185544#46185544) for reference.

**Comment by takluyver** [comment]
I tracked this down as a bug in ipykernel - see ipython/ipykernel#265. 

As a workaround, you can use Alt-Enter (or Esc, Enter) to force it to execute instead of giving you another line.
