### ISSUE TITLE
Parentheses highlight support

### ISSUE THREAD

**Issue by noxdafox** [jupyter/jupyter_console#146]
Both IPython in console mode and qtconsole support parenthesis highlight.

It is particularly useful when dealing with Lisp-like code.

Is there support for such feature in jupyter console?

**Comment by Carreau** [comment]
It should, 

The relevant option is set [here](https://github.com/ipython/ipython/blob/master/IPython/terminal/interactiveshell.py#L348-L366) in IPython, it's a matter of doing the same in the console. Do you want to submit a PR ?

**Comment by noxdafox** [comment]
Sure I'll do.

**Comment by Carreau** [comment]
Perfect, thanks ! If you wish you can send another PR to add a note in docs/changelog.rst, otherwise it will be taken care of when we release 5.3.0.

Thanks !

**Comment by Carreau** [comment]
Closed by #147.

**Comment by noxdafox** [comment]
Didn't know about the changelog, I'll post a PR this evening.

**Comment by Carreau** [comment]
> Didn't know about the changelog, I'll post a PR this evening.

No hurry, we could do a better job at that, and many thing have no entry in changelog. It's just nice to have to promote new features !
