### ISSUE TITLE
Too many white lines in the banner

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_console#155]
## Classic IPython:
<img width="567" alt="screen shot 2018-03-19 at 3 30 00 pm" src="https://user-images.githubusercontent.com/2397974/37601541-8ed97406-2b8a-11e8-87e6-fbf3acdb1620.png">

## Jupyter Console:
<img width="567" alt="screen shot 2018-03-19 at 3 29 35 pm" src="https://user-images.githubusercontent.com/2397974/37601546-91ca1044-2b8a-11e8-8580-bf119f3a984a.png">

**Comment by avirlrma** [comment]
@SylvainCorlay Hey! I'm new here and this one looks quite doable. Can I take this up?

**Comment by SylvainCorlay** [comment]
Sure ! PR welcome.
Thanks for tackling this.

**Comment by avirlrma** [comment]
Update: I haven't been able to start work on this uptil now due to some important uni work, but surely will do this by the end of this weekend.Thanks!
