### ISSUE TITLE
Jupyter-console incompatible with prompt-toolkit 2.0.2

### ISSUE THREAD

**Issue by blfuentes** [jupyter/jupyter_console#158]
After updating the prompt-toolkit package to the version 2.0.2 I get the following error message :

`jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.2 which is incompatible.`

Then if I start a jupyter notebook the message "kernel died" is appearing all the time with this output

```
[I 14:23:58.331 NotebookApp] Kernel started: 60ff14ae-6730-43b2-9c9a-5df4b549aa03
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\IPython\terminal\interactiveshell.py", line 22, in <module>
    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output
ImportError: cannot import name 'create_prompt_application'
[I 14:24:01.294 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
```

I downgraded the prompt-toolkit to the version 1.0.15 and jupyter worked again.

Python 3.6.5
jupyter 1.0.0
jupyter-client 5.2.3
jupyter-console 5.2.0
jupyter-core 4.4.0
ipython 6.4.0

**Comment by homofortis** [comment]
+1

**Comment by yanshen0** [comment]
Same issue here. Hope it can be fixed soon.

**Comment by Carreau** [comment]
Jupyter console needs some love. Most of the same work has been done in ipython/ipython#11177, if any of you have the time, feel free to send PRs.

**Comment by bofeiw** [comment]
Same issue

**Comment by ldmtwo** [comment]
Oddly, it was working fine for a few weeks and suddenly today after rebooting, I got that same error. @blfuentes 's temporary solution worked perfectly. This is the command:
```
sudo pip install 'prompt-toolkit==1.0.15'
```

**Comment by JBlaschke** [comment]
Same here.. And it seems to be interfering with my jupyter notebook

**Comment by petasis** [comment]
When will this be fixed? Its been more than one month that this bug prevents jupyter from running.

**Comment by takluyver** [comment]
When someone gets to it. You can continue using Jupyter with prompt_toolkit 1.0.x in the meantime, so it's not high priority.

**Comment by petasis** [comment]
Ok, I see. It is not a hi-priority, and this is a volunteer project. You assume that everybody knows python, knows how to hack jupyter code (and provide patches), and that the operating system is not pushing any updates.

**Comment by dsblank** [comment]
Need to coordinate the release of a new jupyter-console with ipython, otherwise they each want different versions of prompt_toolkit. 

If this is still an open issue, I'll port jupyter_console to prompt-toolkit later today.

**Comment by Carreau** [comment]
@dsblank someone made https://github.com/jupyter/jupyter_console/pull/161, it just needs review/testing. It's on our todo list, but I'd like to release IPython 7.0 and IPykernel 5.0 first (who use PTK 2.0 as well).

**Comment by jiapei100** [comment]
Same here... Do **NOT** want to downgrade...

**Comment by edesz** [comment]
I think I am getting a different flavor of this problem.

__First attempt to install `jupyterlab`__
Based on [this post](https://github.com/jupyter/jupyter_console/issues/158#issuecomment-403414795), I pin the version of `prompt_toolkit` in my `requirements.txt`

```
prompt_toolkit==1.0.15
jupyter
jupyterlab
```

But when I run
```
pip install -r requirements.txt
```

I get the following

`Could not find a version that matches prompt_toolkit<2.0.0,<2.1.0,==1.0.15,>=1.0.0,>=2.0.0
Tried: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.25, 0.26, 0.28, 0.30, 0.31, 0.32, 0.32, 0.33, 0.33, 0.34, 0.34, 0.35, 0.35, 0.36, 0.36, 0.37, 0.37, 0.38, 0.38, 0.39, 0.39, 0.40, 0.40, 0.41, 0.41, 0.42, 0.42, 0.43, 0.43, 0.44, 0.44, 0.45, 0.45, 0.46, 0.46, 0.47, 0.47, 0.48, 0.48, 0.49, 0.49, 0.50, 0.50, 0.51, 0.51, 0.52, 0.52, 0.53, 0.53, 0.54, 0.54, 0.55, 0.55, 0.56, 0.56, 0.57, 0.57, 0.58, 0.58, 0.59, 0.59, 0.60, 0.60, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.3, 1.0.3, 1.0.4, 1.0.4, 1.0.5, 1.0.5, 1.0.6, 1.0.6, 1.0.7, 1.0.7, 1.0.8, 1.0.8, 1.0.9, 1.0.9, 1.0.10, 1.0.10, 1.0.13, 1.0.13, 1.0.14, 1.0.14, 1.0.15, 1.0.15, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.0.3, 2.0.3, 2.0.4, 2.0.4
There are incompatible versions in the resolved dependencies.`

__Second attempt to install `jupyterlab`__
When I don't specify `prompt_toolkit` in `requirements.txt`

```
jupyter
jupyterlab
```

I get this

`Could not find a version that matches prompt-toolkit<2.0.0,<2.1.0,>=1.0.0,>=2.0.0
Tried: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.25, 0.26, 0.28, 0.30, 0.31, 0.32, 0.32, 0.33, 0.33, 0.34, 0.34, 0.35, 0.35, 0.36, 0.36, 0.37, 0.37, 0.38, 0.38, 0.39, 0.39, 0.40, 0.40, 0.41, 0.41, 0.42, 0.42, 0.43, 0.43, 0.44, 0.44, 0.45, 0.45, 0.46, 0.46, 0.47, 0.47, 0.48, 0.48, 0.49, 0.49, 0.50, 0.50, 0.51, 0.51, 0.52, 0.52, 0.53, 0.53, 0.54, 0.54, 0.55, 0.55, 0.56, 0.56, 0.57, 0.57, 0.58, 0.58, 0.59, 0.59, 0.60, 0.60, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.3, 1.0.3, 1.0.4, 1.0.4, 1.0.5, 1.0.5, 1.0.6, 1.0.6, 1.0.7, 1.0.7, 1.0.8, 1.0.8, 1.0.9, 1.0.9, 1.0.10, 1.0.10, 1.0.13, 1.0.13, 1.0.14, 1.0.14, 1.0.15, 1.0.15, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.0.3, 2.0.3, 2.0.4, 2.0.4
There are incompatible versions in the resolved dependencies.`


System Specifications
```
python 3.7.0
pip ---> latest
```

**Comment by Carreau** [comment]
I just release IPython 7.0 that does support prompt_toolkit 2, now we can review the linked PR, merge it and deployed a new version of QtConsole.

There are just a dependencies between tasks that need to be taken care of... Help welcome in particular any task 9+ in this list still need someone to check manually that it has been done:

https://ipython.readthedocs.io/en/stable/coredev/index.html#update-milestones-on-github

**Comment by Juanlu001** [comment]
@Carreau regarding your [first comment in the issue](https://github.com/jupyter/jupyter_console/issues/158#issuecomment-397022336): I thank all the voluntary effort that you do across the Jupyter ecosystem, and acknowledge that Jupyter devs get lots of undeserved whining from impatient users (I saw another thread where someone was using `<h1>` to make a point, really bad).

However, "feel free to send PRs" not only is hardly a useful explanation of what exactly needs to be done to port jupyter_console to prompt_toolkit 2.0: it also deviates the attention from the main user-facing issue, which is that people get broken installations.

jupyter_console is a package that most users do not use directly, but it gets installed when people do `pip install jupyter` when in fact they might just want `pip install notebook`. As [pip does not solve dependencies](https://github.com/pypa/pip/issues/988) (although at least now we get more informative warnings) this has the unfortunate consequence of dragging prompt-toolkit < 2 and therefore break both the notebook and ipython itself. As a result, even `jupyter console` itself is broken:

```pytb
$ jupyter console
Traceback (most recent call last):
  File "/home/juanlu/.miniconda36/envs/propan36/bin/jupyter-console", line 7, in <module>
    from jupyter_console.app import main
  File "/home/juanlu/.miniconda36/envs/propan36/lib/python3.6/site-packages/jupyter_console/app.py", line 26, in <module>
    from jupyter_console.ptshell import ZMQTerminalInteractiveShell
  File "/home/juanlu/.miniconda36/envs/propan36/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 21, in <module>
    from IPython.core import page
  File "/home/juanlu/.miniconda36/envs/propan36/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/juanlu/.miniconda36/envs/propan36/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/juanlu/.miniconda36/envs/propan36/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 20, in <module>
    from prompt_toolkit.formatted_text import PygmentsTokens
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
```

In my opinion "jupyter_console is incompatible with IPython 7 at the moment because it's not yet ported to prompt-toolkit 2, please upgrade prompt-toolkit and you will be able to safely use IPython and Jupyter Notebook (at the cost of breaking jupyter_console) while someone does the port." would have been a much more useful comment. Even a hotfix of the jupyter metapackage restricting the versions would be a better temporary solution to this problem:

https://github.com/jupyter/jupyter/blob/563951c60d66118a79fa397efb410280f3ce4db7/setup.py#L26-L33

(See also https://github.com/jupyter/jupyter_console/issues/166)

Please take this as constructive criticism, I love what you folks are doing and hope that you continue to enrich this wonderful project <3

**Comment by milesgranger** [comment]
For what it's worth to anyone else, `jupyter-console<5` in the requirements solved this problem for us. :+1:

**Comment by Carreau** [comment]
@Juanlu001, thanks for the constructive criticism, I'll take it into account. 

I just want to no that this issue was open before IPython 7 was released, and it was unknown (at the time) how we would handle the transition.

It is often also relatively hard to balance giving the right amount of information. 
A couple of years ago, it was pointed out to me that I was responding too fast, with too many intimate details, without letting a chance for other to step in. I may have dialed back a bit too much, plus me getting busy on other stuff. 

In general, many project are highly under-maintained in Jupyter, and we may even miss that some people have contributed a lot, and should have received more permission on repo/gotten commit right, or recognition. I have some names in mind, but don't want to say anything without consulting the rest of the team.  

When this is the case, please feel free to remind us of so like @Juanlu001  did, and we'll tust the community and try to foster collaboration. 

Would anyone be willing to send a PR similar to [this one from IPython](https://github.com/ipython/ipython/pull/11326) to this repo, in order to allow anyone the ability to label and close issue, so that there is less bottleneck on the core devs ?

Thanks !

**Comment by panpan2** [comment]
Can someone explain how we can run Jupyter if we are willing to downgrade?
Downgrading with
`pip3 install 'prompt-toolkit<2.0.0,>=1.0.0'`
gives the error
`ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.`
While upgrading with
`pip3 install 'prompt-toolkit<2.1.0,>=2.0.0'`
gives the error
`jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.4 which is incompatible.`
Thanks

**Comment by Carreau** [comment]
Prefer `pip install -U ipython<7` 
If there is ever a new release of IPython 6.x this command will update it. 
Typically, unless you are freezing your dependencies, or create an App you should never pin your dependencies exactly.

**Comment by milesgranger** [comment]
We did `jupyter-console<5` for the time being.

**Comment by s3afroze** [comment]
`pip install 'ipykernel<5.0.0'
`
A solution was posted here
jupyter/notebook#4050

**Comment by s-weigand** [comment]
Quick test in a fresh conda env and at first glimpse `ipython` works (hope that info is helpfull):
OS: Windows 10 x64
Python: 3.6.6
After `pip install jupyter` the installed packages (`pip freeze`) were:
```
backcall==0.1.0
bleach==2.1.4
certifi==2018.8.24
colorama==0.3.9
decorator==4.3.0
defusedxml==0.5.0
entrypoints==0.2.3
html5lib==1.0.1
ipykernel==5.0.0
ipython==7.0.1
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.4.0
nbformat==4.4.0
notebook==5.7.0
pandocfilters==1.4.2
parso==0.3.1
pickleshare==0.7.5
powerline-status===2.6.dev9999-git.b-119c709bf2032814b3dca5fc3c683bc13b4e57eb-
prometheus-client==0.3.1
prompt-toolkit==1.0.15
Pygments==2.2.0
python-dateutil==2.7.3
pywinpty==0.5.4
pyzmq==17.1.2
qtconsole==4.4.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.4.1
tornado==5.1.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
wincertstore==0.2
``` 

Running `pip install 'ipykernel<5.0.0'` resulted in:
```
Collecting ipykernel<5.0.0
  Downloading https://files.pythonhosted.org/packages/22/5e/69b0ae84e0cd7c8d4467e0a7b390c560d8c7642493329b15461b41e20fcc/ipykernel-4.10.0-py3-none-any.whl (109kB)
Requirement already satisfied: traitlets>=4.1.0 in c:\anaconda3\envs\jup-con\lib\site-packages (from ipykernel<5.0.0) (4.3.2)
Requirement already satisfied: jupyter-client in c:\anaconda3\envs\jup-con\lib\site-packages (from ipykernel<5.0.0) (5.2.3)
Requirement already satisfied: ipython>=4.0.0 in c:\anaconda3\envs\jup-con\lib\site-packages (from ipykernel<5.0.0) (7.0.1)
Requirement already satisfied: tornado>=4.0 in c:\anaconda3\envs\jup-con\lib\site-packages (from ipykernel<5.0.0) (5.1.1)
Requirement already satisfied: ipython-genutils in c:\anaconda3\envs\jup-con\lib\site-packages (from traitlets>=4.1.0->ipykernel<5.0.0) (0.2.0)
Requirement already satisfied: six in c:\anaconda3\envs\jup-con\lib\site-packages (from traitlets>=4.1.0->ipykernel<5.0.0) (1.11.0)
Requirement already satisfied: decorator in c:\anaconda3\envs\jup-con\lib\site-packages (from traitlets>=4.1.0->ipykernel<5.0.0) (4.3.0)
Requirement already satisfied: pyzmq>=13 in c:\anaconda3\envs\jup-con\lib\site-packages (from jupyter-client->ipykernel<5.0.0) (17.1.2)
Requirement already satisfied: jupyter-core in c:\anaconda3\envs\jup-con\lib\site-packages (from jupyter-client->ipykernel<5.0.0) (4.4.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\anaconda3\envs\jup-con\lib\site-packages (from jupyter-client->ipykernel<5.0.0) (2.7.3)
Requirement already satisfied: pickleshare in c:\anaconda3\envs\jup-con\lib\site-packages (from ipython>=4.0.0->ipykernel<5.0.0) (0.7.5)
Requirement already satisfied: pygments in c:\anaconda3\envs\jup-con\lib\site-packages (from ipython>=4.0.0->ipykernel<5.0.0) (2.2.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\anaconda3\envs\jup-con\lib\site-packages (from ipython>=4.0.0->ipykernel<5.0.0) (0.3.9)
Requirement already satisfied: jedi>=0.10 in c:\anaconda3\envs\jup-con\lib\site-packages (from ipython>=4.0.0->ipykernel<5.0.0) (0.12.1)
Requirement already satisfied: simplegeneric>0.8 in c:\anaconda3\envs\jup-con\lib\site-packages (from ipython>=4.0.0->ipykernel<5.0.0) (0.8.1)
Requirement already satisfied: backcall in c:\anaconda3\envs\jup-con\lib\site-packages (from ipython>=4.0.0->ipykernel<5.0.0) (0.1.0)
Collecting prompt-toolkit<2.1.0,>=2.0.0 (from ipython>=4.0.0->ipykernel<5.0.0)
  Downloading https://files.pythonhosted.org/packages/e5/c5/f1ee6698bdcf615f171a77e81ca70293b16a6d82285f1760b388b4348263/prompt_toolkit-2.0.5-py3-none-any.whl (334kB)
Requirement already satisfied: setuptools>=18.5 in c:\anaconda3\envs\jup-con\lib\site-packages (from ipython>=4.0.0->ipykernel<5.0.0) (40.4.0)
Requirement already satisfied: parso>=0.3.0 in c:\anaconda3\envs\jup-con\lib\site-packages (from jedi>=0.10->ipython>=4.0.0->ipykernel<5.0.0) (0.3.1)
Requirement already satisfied: wcwidth in c:\anaconda3\envs\jup-con\lib\site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=4.0.0->ipykernel<5.0.0) (0.1.7)
jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.5 which is incompatible.
Installing collected packages: ipykernel, prompt-toolkit
  Found existing installation: ipykernel 5.0.0
    Uninstalling ipykernel-5.0.0:
      Successfully uninstalled ipykernel-5.0.0
  Found existing installation: prompt-toolkit 1.0.15
    Uninstalling prompt-toolkit-1.0.15:
      Successfully uninstalled prompt-toolkit-1.0.15
Successfully installed ipykernel-4.10.0 prompt-toolkit-2.0.5
```
And the installed packages after were:
```
backcall==0.1.0
bleach==2.1.4
certifi==2018.8.24
colorama==0.3.9
decorator==4.3.0
defusedxml==0.5.0
entrypoints==0.2.3
html5lib==1.0.1
ipykernel==4.10.0
ipython==7.0.1
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.4.0
nbformat==4.4.0
notebook==5.7.0
pandocfilters==1.4.2
parso==0.3.1
pickleshare==0.7.5
powerline-status===2.6.dev9999-git.b-119c709bf2032814b3dca5fc3c683bc13b4e57eb-
prometheus-client==0.3.1
prompt-toolkit==2.0.5
Pygments==2.2.0
python-dateutil==2.7.3
pywinpty==0.5.4
pyzmq==17.1.2
qtconsole==4.4.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.4.1
tornado==5.1.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
wincertstore==0.2
```

**Comment by Carreau** [comment]
That is extremely weird. Downgrading IPykernel seem to upgrade
prompt_toolkit. My guess is on the first pass pip install the version of
prompt_toolkit that match jupyter_console, any update prompt toolkit on
second invocation, thus breaking Jupyter_console.

This may even be a random order of solving things so this may be broken for
some users.

So either one need to
1) downgrade IPython if you wish to keep jupyter_console working
2) upgrade prompt_toolkit if you want new IPython feature
3) upgrade Jupyter console (to master)

Downgrading IPykernel seem to lead to (2) for whatever reason but should
likely not be done as it will deactivate some new IPython features.


Thanks !

**Comment by ankurgadgilwar** [comment]
I am getting an error `ImportError: No module named 'prompt_toolkit.formatted_text'` what does this mean? I need to explicitly install prompt_toolkit?? 
If yes, then please help with this.

**Comment by s-weigand** [comment]
@ankurgadgilwar see #167

**Comment by alfsalte** [comment]
I have a related issue but it is just a notch weirder...

ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.

The problem is that python -m pip list and python3 -m pip list both tells me I have version 2.0.5 of prompt-toolkit. Yes, I did have version 1.0.15 but I uninstalled it and installed version 2.0.5.

So what's wrong?

**Comment by Personr** [comment]
> I am getting an error `ImportError: No module named 'prompt_toolkit.formatted_text'` what does this mean? I need to explicitly install prompt_toolkit??
> If yes, then please help with this.

I found a solution to this problem here : https://stackoverflow.com/questions/52551878/problems-upgrading-ipython-prompt-toolkit-incompatibilities

> The solution for me was to pip uninstall prompt-toolkit and pip install prompt-toolkit. This uninstalled v1.0.5 and installed v2.0.4.

**Comment by fofoni** [comment]
I'd like to point out that I googled the error message that I got whenever I tried `pip install jupyter` in an empty virtual environment, and the first result was this issue page. I got here without realizing that jupyter and jupyter-console are actually different things, and I believe that many people reading this may be in the same situation, so I'll quote the comment by @Juanlu001 that saved me:

> jupyter_console is a package that most users do not use directly, but it gets installed when people do `pip install jupyter` when in fact they might just want `pip install notebook`. As [pip does not solve dependencies](https://github.com/pypa/pip/issues/988) (although at least now we get more informative warnings) this has the unfortunate consequence of dragging prompt-toolkit < 2 and therefore break both the notebook and ipython itself.

All I had to do was `pip install notebook` *instead* of `pip install jupyter`. The command `jupyter notebook` still works, I still don't know exactly what `jupyter_console` is, but I got a working environment again :)

**Comment by ankurgadgilwar** [comment]
@Personr Installing the package explicitly resolved the issue for me. Also, I disabled the ad blocker on my browser, restarted it and Voila! it worked. try `pip install prompt-toolkit==2.0.1`

**Comment by Carreau** [comment]
Jupyter Console 6 should have been released by @blink1073 yesterday, this should not be an issue anymore (we hope). Thanks @blink1073 

Let us know if you are still experiencing issues. We also just gave commit right to this repository to @dsblank who have been an advocate of Jupyter and helped managed the community for a number of years. This was long overdue. See #170 



We are still working hard on empowering the community to move packages forward without blocking on the core team, and hope that this is as small step forward.  

Thanks all, congrats to @dsblank

**Comment by Carreau** [comment]
@dsblank I'll let you the honor of closing the issue as this is one of your newly acquired powers.

**Comment by dsblank** [comment]
Make it so. 😀

**Comment by dsblank** [comment]
(Please reopen if you have any issues.)

**Comment by Carreau** [comment]
> (Please reopen if you have any issues.)

Or ask for it to be re-opened if necessary. Sometime issues can only be reopened by contributors with commit rights.

**Comment by artgoldberg** [comment]
Jupyter end user here experiencing "ImportError: cannot import name 'create_prompt_application'".  Argh! Should be preparing my class. Serves me right -- I should have a Docker image with working jupyter, and not install it from pip every time, which makes me vulnerable to release bugs. But this appears to fix it:

    pip uninstall prompt-toolkit 
    pip install prompt-toolkit==1.0.15 
    pip uninstall jupyter-console 
    pip install jupyter-console==5.2.0

**Comment by sawan** [comment]
> @Carreau @dsblank I'm still having this issue on a fresh pip install of jupyter (ubuntu 18.04, Python 3.6.6). It shows I have jupyter_console 6.0.0 installed but I'm still having the import issue. Let me know what I can provide to help resolve this.

Yes, still seeing this error....

**Comment by blink1073** [comment]
@bgyarfas, @sawan, what is the output of `pip list` in the new environment?

**Comment by Idodox** [comment]
@dsblank firstly thanks for your and the team's hard work.
at the moment, I'm still seeing this issue.
As suggested before, running
` sudo pip install 'prompt-toolkit==1.0.15'`
fixed the problem.

**Comment by DeFeNdog** [comment]
What worked for me was to uninstall Jupyter since I didn't need it at the time:

Remove this guy
`pip uninstall jupyter`

Uninstall problematic version
`pip uninstall prompt_toolkit`

Remove old "broken version"
`pip uninstall ipython`

Let pip install with it's preferred dependencies
`pip install ipython`

**Comment by shij316** [comment]
I still have the problem, even after set prompt-toolkit==1.0.15

**Comment by HarshaLaxman** [comment]
> pip install 'prompt-toolkit==1.0.15'

For Windows:
pip install prompt-toolkit==1.0.15

**Comment by Arkelis** [comment]
For me, upgrading ipython did the tric (I only installed jupyter before). (Fedora 28)
```pip3 install --upgrade --user ipython```

**Comment by derrysan7** [comment]
if you're using windows and don't want the headache of updating dependency manually by using pip, just update your jupyter console using:
`conda install -c anaconda jupyter_console`

**Comment by MXWXZ** [comment]
> pip3 install --upgrade --user ipython

This works for me in Ubuntu 18.04.

**Comment by ngocketit** [comment]
You also may need to do this: `pip3 install --upgrade --user jupyter-console`

**Comment by Abdelrahman995** [comment]
@ldmtwo worked for me thanks !

**Comment by samra-irshad** [comment]
@artgoldberg thanks, it worked!

**Comment by amundv** [comment]
```pip3 install --upgrade --force jupyter-console```
Worked for me

**Comment by jbulow** [comment]
I have the same issue. Have read all comments here bu can't get rid of the error message. Using Ubuntu 18.04. Is there a known reproducible way to make it work on this OS?

**Comment by puramchendrasekhar1** [comment]
> Oddly, it was working fine for a few weeks and suddenly today after rebooting, I got that same error. @blfuentes 's temporary solution worked perfectly. This is the command:
> 
> ```
> sudo pip install 'prompt-toolkit==1.0.15'
> ```

Thank you man, this worked for me

**Comment by Valuebai** [comment]
> `pip3 install --upgrade --force jupyter-console`
> Worked for me
windows10 x64, the command worked for me too
`pip install --upgrade --force jupyter-console`

**Comment by AlexZettler** [comment]
If this hasn't been fixed yet, may I take my hand at working on a solution?

**Comment by Carreau** [comment]
> If this hasn't been fixed yet, may I take my hand at working on a solution?

Of course, and sorry if we can be slow to review. Feel free to ping us if necessary.

**Comment by sgillen** [comment]
> sudo pip install 'prompt-toolkit==1.0.15'

worked just fine for me with no sudo too.

**Comment by October22** [comment]
The new version of prompt-toolkit(< 2.0) is 1.0.16(update Apr 12, 2019)

**Comment by robertlugg** [comment]
Hi future readers, per this:
https://medium.com/@supachaija/how-to-fixed-modulenotfounderror-prompt-toolkit-formatted-text-on-jupyter-python-b51f2132ac1c

Using this version works (I've also confirmed)
ipython==6.5.0

Presumably you are using an old version, but if you are just looking to get something running...

**Comment by tinmarino** [comment]
`pip3 install --upgrade --user jupyter` worked for me installing:
`installed prompt-toolkit-2.0.10`
on Ubuntu 19.10 / Linux 5.3.0-24-generic

**Comment by Ransaka** [comment]
Try pip install ipython --upgrade
this works for me;)

**Comment by jixuebaby** [comment]
> > `pip3 install --upgrade --force jupyter-console`
> > Worked for me
> > windows10 x64, the command worked for me too
> > `pip install --upgrade --force jupyter-console`

Also, worked for me, Thanks
