### ISSUE TITLE
Make a new release on PyPi

### ISSUE THREAD

**Issue by s-weigand** [jupyter/jupyter_console#167]
The current version of `jupyter-console` on PyPi (5.2.0, Aug 21, 2017 ) is breaking the `jupyter` installation (see #166 ), because of the dependency conflict in `prompt-toolkit` with `ipython>=7.0`.
Thus a new version should be released on PyPi, to prevent users from having touble.

Also a check of the `ipython` version on installation would be good, to inform user of legacy ipython `ipython<7.0` that they need to install `jupyter-console<=5.2`. Or at least set min python version to 3.5 so it compatible with `ipython>=7.0` . I don't know what the best tactics is for this.

**Comment by vmehera123** [comment]
@s-weigand doesn't work on fresh ubuntu 18.04

> Since i saw it come up some times by now, there are two temporary workarounds:
> 
> 1. Downgrade `ipython`:
>    `pip install -U ipython<7.0`
> 2. Upgrade `jupyter-console` to current master:
>    `pip install git+https://github.com/jupyter/jupyter_console`

doesn't work (fresh ubuntu 18.04)

**Comment by blink1073** [comment]
@Carreau @ivanov if you add me to PyPI I can make a release later today.

**Comment by blink1073** [comment]
(blink1073)

**Comment by Carreau** [comment]
Should be done (from my phone so I sure).


Many thanks !

**Comment by blink1073** [comment]
Yep, I got the email from PyPI

**Comment by blink1073** [comment]
6.0 is available on PyPI and working nicely with `pip install jupyter` in a clean conda environment.  However, I also released an errant 5.4.0 that I don't have the ability to remove...

**Comment by blink1073** [comment]
Conda release in flight: https://github.com/conda-forge/jupyter_console-feedstock/pull/10

**Comment by dsblank** [comment]
Thanks all! Can this be closed?

**Comment by blink1073** [comment]
Yep!  I made #174 to track my errant release.
