### ISSUE TITLE
jupyter_console-6.1.0: Distribution tarball missing `scripts` folder

### ISSUE THREAD

**Issue by jeeger** [jupyter/jupyter_console#222]
Greetings! I'm trying to install jupyter console on Gentoo. Gentoo uses the pypi tarball to install the packages. However, the 6.1.0 [tarball](https://files.pythonhosted.org/packages/e9/54/da5cd731e5845b529838b42666282fd59b282691407f529580383c62d859/jupyter_console-6.1.0.tar.gz) is missing the `scripts/` folder, which means that no `jupyter_console` script will be installed. 

I could work around this by using a bdist target to regenerate the script, but this seems like a bug to me. Please advise.

**Comment by Carreau** [comment]
Thanks for packaging this on Gentoo, 

And sorry I'm trying to revive this repository. I've created #227 that should fix this in the next release. 

I think in the long term we should likely not include scripts but rely on entry points, setuptools is suppose to know how to take care of that. At least I never had complaints about IPython and that's how it does it.

let me know if #227 works for you, and I'll try to keep this open to think about how to properly update that in the long run. 

If there is anything that we can keep in this repository to make the ebuild easier to maintain (or even have the ebuild file as part of this repo) let me know.

**Comment by jeeger** [comment]
Hey! Thanks for fixing this!

Using setuptools is exactly the fix that the Gentoo maintainer for the package added (I'm not the maintainer, I just found the bug). The Gentoo bug report is here: https://bugs.gentoo.org/734786. I think this will make packaging jupyter console much easier.
