### ISSUE TITLE
4.0.1 and main

### ISSUE THREAD

**Issue by aklaver** [jupyter/jupyter_console#24]
Just upgraded to 4.0.1 as part of pip install jupyter and got this:

aklaver@panda:~/py_virt/pandas> jupyter console
Traceback (most recent call last):
  File "/usr/bin/jupyter-console", line 7, in <module>
    from jupyter_console import main
ImportError: cannot import name main

When I downgraded to 4.0.0:

aklaver@panda:~/py_virt/pandas> sudo pip install jupyter-console==4.0.0

it worked:

aklaver@panda:~/py_virt/pandas> jupyter-console
Jupyter Console 4.0.0

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic

In [1]:

**Comment by minrk** [comment]
Typo in #22, sorry about that. Fixed by #25, and will cut 4.0.2 shortly.
