### ISSUE TITLE
Any chance we could get a release for this soon?

### ISSUE THREAD

**Issue by NeilGirdhar** [jupyter/jupyter_console#256]
https://github.com/jupyter/jupyter_console/pull/244 is a very big deal for those of us with a broken jupyter.  If it's not too much trouble, we would love to see a new release :smile: 

Maybe once the 3.10 bugs (https://github.com/jupyter/jupyter_console/issues/245, which may be eventually fixed by https://github.com/jupyter/jupyter_console/pull/258) are squashed, that would be an ideal time to release?

**Comment by davidbrochart** [comment]
@Carreau Indeed I think a release would be very welcome, any chance you could do one soon?
Otherwise, I would be happy to do it if you give me the rights. I can also open a PR in order to switch this project to use [Jupyter Releaser](https://github.com/jupyter-server/jupyter_releaser).

**Comment by Carreau** [comment]
Just made you admin on github, and I can add you on PyPI, what's your username ?
I can try to make a release as well.

**Comment by davidbrochart** [comment]
My PyPI login is: davidbrochart
Thanks!

**Comment by Carreau** [comment]
Added.

**Comment by davidbrochart** [comment]
Thanks @Carreau, I just released v6.4.1.
