### ISSUE TITLE
Jupyter console not usable on Windows

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyter/jupyter_console#26]
On Windows, `jupyter console` is not usable, because it is 'not blocking the command prompt'. This is a similar issue as https://github.com/jupyter/notebook/issues/367. But, where the issue is not critical for the notebook, it makes the console just unusable.

Small illustration:

![capture1](https://cloud.githubusercontent.com/assets/1020496/9766128/a874bc8a-5717-11e5-86a4-8de0ef8b8f9e.PNG)

At the moment I type `x`, it returns to the command prompt, where `x` is not defined.

While typing, the cursor randomly switches between the jupyter prompt and the normal command prompt.

**Comment by jorisvandenbossche** [comment]
BTW, this is in a fresh conda environment only installing jupyter (python 2.7, Windows 7)

**Comment by jorisvandenbossche** [comment]
I think this is fixed by https://github.com/jupyter/jupyter_core/pull/54

**Comment by minrk** [comment]
@jorisvandenbossche indeed it is. Thanks, I had lost track of this one.
