### ISSUE TITLE
completion shows traceback if previous prompt was interrupted with Ctrl-C

### ISSUE THREAD

**Issue by anntzer** [jupyter/jupyter_console#27]
```
$ jupyter console
Jupyter Console 4.0.0

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
[ZMQTerminalIPythonApp] Loading IPython extension: autoreload
[ZMQTerminalIPythonApp] Loading IPython extension: line_profiler
[ZMQTerminalIPythonApp] Loading IPython extension: memory_profiler

In [1]: # <--- Ctrl-C
KeyboardInterrupt

In [1]: cd ---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/usr/lib/python3.4/site-packages/ipykernel/eventloops.py in process_stream_events()
     23         from IPython.core.interactiveshell import NoOpContext as context
     24 
---> 25     def process_stream_events():
        global process_stream_events = undefined
     26         while stream.getsockopt(zmq.EVENTS) & zmq.POLLIN:
     27             with context():

KeyboardInterrupt:

<correct list of completion follows>
```

Arch Linux standard packages:
jupyter-client==4.0.0
jupyter-console==4.0.0
jupyter-core==4.0.4

**Comment by minrk** [comment]
What is your pyzmq version? Can you try with jupyter-client 4.1 and jupyter-console 4.0.3? There's a chance a signaling fix may have resolved this. I haven't been able to reproduce this one. Also try with no configuration at all:

    IPYTHONDIR=/tmp/ip JUPYTER_CONFIG_DIR=/tmp/jp jupyter console

just to be sure no extensions are causing peculiarity.

**Comment by anntzer** [comment]
pyzmq is 14.7.0.
The issue is fixed with the versions you give and a clean profile.  Feel free to close.
As an unrelated side note, are the version numbers of jupyter_core, jupyter_client and jupyter_console going to evolve out of sync from each other?  This seems a bit confusing :/

**Comment by minrk** [comment]
@anntzer yes, they are independent projects, and will have totally different versions as time goes on.
