### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_console#3]
There currently aren't any. We should have:

- [x] A brief narrative introduction
- [x] Documentation of config options
- [x] Docs building on RTD

I don't think API docs are a priority here - it's not clear that this package has anything we'd really consider public API.

**Comment by minrk** [comment]
Do you think #17 is sufficient for 4.0 docs?

**Comment by takluyver** [comment]
Yes, I think so.

**Comment by minrk** [comment]
Thanks! Then I'll cut the release now.
