### ISSUE TITLE
jupyter console does not look for configuration files in user directory (but in current one)

### ISSUE THREAD

**Issue by mapio** [jupyter/jupyter_console#31]
If you run 

    $ echo 'exit' | jupyter console --debug 2>&1 | grep $HOME/.jupyter

you get no output (if you grep `.ipython` it turns out that those are searched, instead). On the other hand, as an example of correct output, if you run

    $ jupyter notebook --debug 2>&1 | grep $HOME/.jupyter

you get as output something like

	[D 19:21:30.633 NotebookApp] Searching [u'/Users/santini', '/Users/santini/.jupyter', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
	[D 19:21:30.634 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/santini/.jupyter
	[D 19:21:30.634 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/santini/.jupyter
	[D 19:21:30.634 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/santini/.jupyter
	[D 19:21:30.634 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/santini/.jupyter

I'm using 

	$ jupyter --version
	4.0.6
	$ jupyter console --version
	4.0.3

**Comment by takluyver** [comment]
It looks like this is because the Jupyter console application class was inheriting from the IPython application. I've opened #45 to fix that.
