### ISSUE TITLE
Exit from console without shutting down kernel

### ISSUE THREAD

**Issue by danieljl** [jupyter/jupyter_console#34]
Supposed I open a new console using existing kernel by running:
`jupyter console --existing`

If I type `exit` or `quit`, both console and kernel terminate. Is it possible to exit from that new console without shutting down the existing kernel? Thanks.

**Comment by takluyver** [comment]
Yep, type:

```python
exit(keep_kernel=True)
```

If you're doing this often enough that you want a shortcut, you can make a function or a custom magic that calls that.

**Comment by danieljl** [comment]
@takluyver Thanks!
