### ISSUE TITLE
bash interactive - cannot quit with ctrl+C

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_console#39]
just tried to call top with "! top" inside jupiter 4.1.0.dev  and I get stuck. Ctrl+C is not working in this case.
Only way to do it is killing the process, after that i return to the console.

jupiter 4.1.0.dev
python 3.5.1
ipython 4.0.1

**Comment by ocehugo** [comment]
I just remembered that with ipython console this also happens and have saw some issues regarding this....

**Comment by takluyver** [comment]
If you mean the process you start by typing `ipython console`, that's the same thing - `jupyter console` is just the new name for it.

It looks like jupyter_console is failing to send SIGINT to the kernel when you press Ctrl-C - I can see the same problem when running `time.sleep(10)`. I'll look into it.

**Comment by takluyver** [comment]
#43 should fix this.
