### ISSUE TITLE
segfault after KeyboardInterrupt

### ISSUE THREAD

**Issue by ohadle** [jupyter/jupyter_console#41]
I don't know how useful this bug report is, since it'll be hard for someone else to reproduce.
I keep getting segfaults when running a memory and compute intensive program (deep learning) in ipython 4.0.1, and pressing ^C in a loop:
```
KeyboardInterrupt:

In [3]: [1]    18011 segmentation fault  ipython-2.7 --pylab
```
It usually happens doing a Keras (Theano) run, so I'm not plotting anything at that moment.

**Comment by minrk** [comment]
It's quite unlikely for this to be IPython-related (I can't see how it would be Jupyter-console related). I'm guessing it's the low-level code that's not handling SIGINT properly. Do you see the same thing when you interrupt the same code as a plain Python script?

**Comment by ohadle** [comment]
I'll check, thanks!

**Comment by takluyver** [comment]
Closing as this hasn't moved in 3 months, and we think it's unlikely that it's actually a bug in Jupyter or IPython.
