### ISSUE TITLE
bash interactive - cannot see screen update

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_console#42]
using jupyter-qtconsole the user is not able to see the screen updates when calling bash commands with !.

A simple "! top" in qt console executes the command but the output in the screen is scrambled and not visible at all.

This differs from the terminal console behaviour #39, since from here we are able to terminate the command with ctrl+c.

jupiter 4.1.0.dev
python 3.5.1
ipython 4.0.1

**Comment by takluyver** [comment]
The Qt console is not a full terminal emulator. Commands like `top` or `vim` that take over the full terminal window won't work properly. I don't think we have any plans to support them - recreating a full terminal emulator is a lot of work.

**Comment by takluyver** [comment]
Also, there's a separate repository for the Qt console:
https://github.com/jupyter/qtconsole

If you have issues with the Qt console, please file them there. This repository is specifically for the terminal console you start with `jupyter console`.
