### ISSUE TITLE
How to exit from jupyter console --existing

### ISSUE THREAD

**Issue by szs8** [jupyter/jupyter_console#48]
After I connect to an existing notebook kernel from a console, CTRL-C kills the kernel.

How do I exit the console without killing the kernel?

**Comment by takluyver** [comment]
You can do `exit(keep_kernel=True)`. I'm a bit surprised that doesn't happen automatically when you press Ctrl-D, though (I assume you meant that rather than Ctrl-C, which shouldn't kill the kernel at all).

**Comment by lentils** [comment]
Hi guys, I was wondering the same issue myself and found this issue. I usually use `jupyter console --existing` as a nice way to tap into a session and hack away in a repl before writing something more formal in a notebook cell, so I frequently find myself ending the session and killing my kernel in the process.

It looks like the console's `exit` is an instance of `IPython.core.autocall.ZMQExitAutocall`, which according to [the call signature](https://github.com/ipython/ipython/blob/master/IPython/core/autocall.py#L68) has `keep_kernel` set to `False`. There are a lot of moving parts to this so I won't make any assumptions here, but I agree with @takluyver in that I'd expect `True` by default. Of course, there may be a very good reason for keeping it `False` by default!

**Comment by dalejung** [comment]
I recall it only killing kernels that it owned. Am I misremembering?

**Comment by dalejung** [comment]
fyi. 

```python
from ipykernel.zmqshell import ZMQInteractiveShell
from IPython.core.autocall import ZMQExitAutocall
class KeepAlive(ZMQExitAutocall):
    def __call__(self):
        super().__call__(True)

ZMQInteractiveShell.exiter = KeepAlive()
```

in my `jupyter_console_config.py` gives me the behavior that I want. You can't keep an owned kernel alive so there's no worry of defaultig to keeping zombie kernels around.

**Comment by Maltimore** [comment]
I have the same problem as the original poster and the fix proposed by @dalejung does not seem to fix it for me. Any other suggestions?

**Comment by tinmarino** [comment]
To make an alias calling `exit(keep_kernel=True)`
Close from dalejung (which did not work for me), I wrote an ipython_startup.py.
This file must be located in PYTHONSTARTUP path.

`def` exit_func():
    """ Override old exit to keep kernel alive if possible """
    try:
        exit_legacy (keep_kernel=True)
        print "Exit front-end"
    except:
        exit_legacy()
        print "Exit Old way"
    return

import IPython.core.autocall as autocall

class ExitClass(autocall.IPyAutocall):
    """ Supposingly an autcall class """
    def __call__(self):
        exit_func()


exit = xit = ExitClass()`



:mouse:

**Comment by takluyver** [comment]
@yangle's changes in #127 make it so that Ctrl-D won't kill a kernel that the console doesn't own. I think that fixes this.
