### ISSUE TITLE
console history not working

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_console#49]
The history of commands in jupyter console is not working as expected.

As soon as the user leave the start folder, the history appears to be lost. How to reproduce:

`python console`
`#ctrl+R show up the history`
`cd /tmp`
`#ctrl+r do not show history anymore`

as expected, running ipython without the console option do not raise this problem.

local kernel

→ ipython --version
4.0.1
→ python3 --version
Python 3.5.1
→ jupyter-console --version
4.1.0.dev

**Comment by minrk** [comment]
What OS+version? The repro steps do not work for me (ctrl-R continues to work as expected), so there must be something more to it.

**Comment by ocehugo** [comment]
OSX El Capitan
I also forgot to mention that my sqlite history file is in non default folder:

c.HistoryManager.enable = True
c.HistoryManager.hist_file = 'folder'

**Comment by takluyver** [comment]
I don't think that should make a difference; it should be loading recent history into memory for Ctrl-R search when you start the console, so if it works at one point, I'm not sure how cd-ing could stop it working.

**Comment by ocehugo** [comment]
Hello again,

I just realised that the change the folder is not the culprit. In fact after the first command is sent to the console you "lost" completely the previous session history.

So if you start working in something new you get the history from the current session but the previous session commands are gone (you can only access the previous ones running ctrl+R in in the first line of the console and after that is gone).

**Comment by takluyver** [comment]
That's bizarre. Does it happen regardless of the command you type? E.g. if you just type `2` and press enter, do you still lose history? Does the same happen in ipython?

**Comment by ocehugo** [comment]
In Ipython everything is fine. Just checked on qtconsole and it's working also. for now only terminal consoles are affected. I'm suspecting something related to readline/OSX based on the ipython install notes, but i had follow all the requirements ( gnureadline installed) and don't know much about it.

**Comment by takluyver** [comment]
We do do a bit of fiddling with readline after each cell is executed to store multiline history. Maybe that's causing it. Can you try running with this option:

```
jupyter console --InteractiveShell.multiline_history=False
```

**Comment by ocehugo** [comment]
Solved! Now i fell an idiot about not trying this obvious thing, but what save me from being a lazy one is that this should work out of the box (default value is True ). hehehe

**Comment by takluyver** [comment]
Well, it's not really solved - that's not what the option's supposed to do, so we've just narrowed down where the bug is.

Can you try editing your installed copy of `jupyter_console`. Find [this line](https://github.com/jupyter/jupyter_console/blob/cb264759bbdfa6eb943d6400ccb12c4ff1267e39/jupyter_console/interactiveshell.py#L658), and add before it:

```python
print(hlen_b4_cell, self.readline.get_current_history_length())
```

Then try running it, and post the numbers that you see after running the first command.

**Comment by takluyver** [comment]
(I mean run it without setting the option, so that you do see the bug again)

**Comment by ocehugo** [comment]
Sorry for the delay (weekend ;) ) . No numbers are showed. Numbers are only showed after Ctrl+C. The first ctrl+C return me `1 1`.

**Comment by takluyver** [comment]
Aha. The `0 950` means it thinks that the history was completely empty before that cell, when actually there were 949 entries. That's why it's stripping them out.

Can you try swapping over [these two lines](https://github.com/jupyter/jupyter_console/blob/cb264759bbdfa6eb943d6400ccb12c4ff1267e39/jupyter_console/interactiveshell.py#L573-L574) and see if it makes a difference?

I'm not quite sure why `refill_readline_hist()` is there at all - it should be called earlier in startup (in `init_readline()`), and for me it is. I guess that somehow it's not running at that point for you, which exposes this bug.

**Comment by ocehugo** [comment]
Swapping it : 
```In [1]: A=range(0,5)
943 944
A=range(0,5)
944

In [2]: abc=10
944 945
abc=10
945
```

and the history search is working without the multiline option set to False ;)

**Comment by takluyver** [comment]
Great! And just to check, if you comment out `the line there with `self.refill_readline_hist()`, do you see no history at all from previous sessions? We expect history to be filled in `init_readline()` in the parent class; I'm not sure why it wouldn't be.

**Comment by ocehugo** [comment]
exact. no history after commenting out the refill method

**Comment by takluyver** [comment]
What versions of IPython and jupyter_console do you have? If they're not up to date, can you update and check if it still happens?

**Comment by ocehugo** [comment]
upgrade ipython-4.0.3
downgrade jupyter 4.0.6

and history is not working at all. I cannot go back to previous history from the first line in the console. Qt console history works .

Upgrade jupyter to (4.2.0):
nothing change from the report ( i can access history form the first line, after that it's lost again). Qt console history works.

**Comment by takluyver** [comment]
It's specifically [jupyter_console](https://pypi.python.org/pypi/jupyter_console) that affects this - Jupyter is a collection of packages that are released independently (though they all started at 4 when we split them out). The latest version of that is 4.1.0. Is that what you're using? You can check with `jupyter console --version`.

**Comment by ocehugo** [comment]
→ jupyter-console --version
4.2.0.dev

I was using 4.1.0 before (as reported), I just run the pip3 git+gitrepo@master

**Comment by takluyver** [comment]
Right, sorry, I must have missed the version number before. I'll investigate further in the morning (UK time).

**Comment by takluyver** [comment]
Apologies for the delay. I lost interest in working out what was going on, but #58 should fix it (I swapped over the lines I mentioned). I'm planning to rewrite quite a bit of jupyter_console for 5.0 anyway (see #57).
