### ISSUE TITLE
Please add ipython %cpaste magic

### ISSUE THREAD

**Issue by languitar** [jupyter/jupyter_console#50]
I am using vim-slime to send things to ipython. Now I'd like to transition this approach to jupyter console, but the `%cpaste` magic is missing here.

**Comment by takluyver** [comment]
Do you need to transition? `ipython` will continue to exist, it's not being replaced by `jupyter console`.

**Comment by languitar** [comment]
I'd like to use features of juptyer as well. Or is it possible to start a usual ipython session and connect a qtconsole to that sessions? The usual ipython interpreter does not know `%connect_info`.

**Comment by languitar** [comment]
And in any case, this still sounds like a useful feature to me in a non-graphical shell. Why remove it?

**Comment by takluyver** [comment]
It wasn't removed, it's just a feature of terminal IPython that didn't readily translate to the two-process model.

**Comment by languitar** [comment]
Ok, and I cannot attach a jupyter component to a normal ipython instance?

**Comment by takluyver** [comment]
No, plain terminal IPython doesn't use the kernel machinery which other frontends can connect to.

**Comment by takluyver** [comment]
`jupyter_console` in master now has an interface built on `prompt_toolkit`, which can handle pasting multiple lines without needing separate mechanisms like `%cpaste`. So I don't think we need to add cpaste in jupyter_console. I'm closing the issue, but we can reopen it if you think there is still a need for something like that.
