### ISSUE TITLE
Documented option for autoindent wrong

### ISSUE THREAD

**Issue by languitar** [jupyter/jupyter_console#51]
The documentation on readthedocs explains the following config option for the console:
```
InteractiveShell.autoindent : CBool
```
I do not even have `InteractiveShell` as a config object in jupyter console 4.0.3. What exists is `ZMQInteractiveShell`. In that object, `autoindent` exists, is set to `False` and still the shell auto-indents.

**Comment by takluyver** [comment]
The config system works with class inheritance, so you can set options on `InteractiveShell` and it affects any more specific subclasses.

Setting `c.InteractiveShell.autoindent = False` in `~/.jupyter/jupyter_console_config.py` does work for me.

jupyter console in particular inherits a lot of config options from ipython, not all of which it actually uses. We are working to disentangle them, but it's not a top priority for anyone at the moment.

**Comment by languitar** [comment]
But trying to set `InteractiveShell.autoindent` using the `%config` magic does not have any effect. I only need this for certain sessions. So setting this in the global config is not what I want.

**Comment by takluyver** [comment]
The `%config` magic can only act in the kernel, and indenting is a frontend feature. I know this is all rather awkward - the config system was designed like that before we thought of splitting it into two processes.

**Comment by languitar** [comment]
Ok, this definitely needs some more documentation ;)

Is there any way to configure this for just a single session?

**Comment by languitar** [comment]
Do I need to set anything more in `~/.jupyter/jupyter_console_config.py` than:
```
c = get_config()
c.InteractiveShell.autoindent = False
```

This doesn't disable auto indentation for me. Entering `bla:<CR>` sends me into a new line indented by four spaces.

**Comment by languitar** [comment]
Ok, but setting this on the command line works.

**Comment by takluyver** [comment]
Right, the released version was looking for config in the wrong place, but it's been fixed in master (#45). We should probably make a new release, that's a pretty major bug.

**Comment by languitar** [comment]
Ok. At least I can now reuse my old vim-slime, tmux magic to get changed code into a kernel and have a second qtconsole for interactive work.

**Comment by takluyver** [comment]
Our 4.1 release did get the config file for this in the right place, so it should now be correctly configurable. Using the `%config` magic still won't work, but that's not exactly a bug, and a larger confusing thing with Jupyter as a whole.
