### ISSUE TITLE
Autoindentation not working

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_console#52]
We switched to use the is_complete messages to determine when to execute input (#35). These messages also give a suggested indentation level for the next line of input, but we don't actually wire that up to adding the indentation at the prompt.

Ping @dsblank

**Comment by dsblank** [comment]
If I knew how, I would!

**Comment by dsblank** [comment]
+1 Very nice, @takluyver ! Makes https://github.com/Calysto/calysto_scheme and other languages feel like they are in a first-class console. Thanks!
