### ISSUE TITLE
'pyreadline' on windows now required starting 4.1.0 ?

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyter_console#55]
Christoph Gohlke doesn't advise it (`(unstable, deprecated), a ctypes-based readline for Windows.`), and it was not required before.

==> isn't there any other solution than this https://github.com/jupyter/jupyter_console/commit/c356a778c2ffc73b466203b7a48a108a0f786fc2 ?

**Comment by takluyver** [comment]
It has always really been a requirement on WIndows, we just forgot to list it as a dependency before. The experience without it would be terrible - no tab completion, no command history, no colours and potentially ugly escape codes visible when it tries to use colour.

We have a plan to move away from pyreadline - see ipython/ipython#9118 for the start of that - which will hopefully be in place for 5.0 of both ipython and jupyter_console. But for now, yes, pyreadline is required.
