### ISSUE TITLE
kernel banner missing

### ISSUE THREAD

**Issue by sn6uv** [jupyter/jupyter_console#59]
The docs on 'Making simple Python wrapper kernels' state, "The ‘banner’ is displayed to the user in console UIs before the first prompt". It works for the qtconsole but not the terminal console.

Originally jupyter/jupyter_client#123

**Comment by Carreau** [comment]
Thanks for reopening here !

**Comment by sn6uv** [comment]
Can we reopen this one? PR #60 solved part of it but the banners still aren't being displayed.

**Comment by takluyver** [comment]
This seems to be working now - I think it was fixed by #68 for 5.0.
