### ISSUE TITLE
Add support for vi type interaction

### ISSUE THREAD

**Issue by jvtrudel** [jupyter/jupyter_console#6]
Am i wrong or there is no support for vi commands in ipython and jupyter?
Is it the right project to request this feature improvement?

**Rational of the request**

vi, vim and gvim are well known text editors used by a large community of developers. The use of different interacting mode and the large set of flexible and powerful shortcuts make it a very efficient tool for developers.

The ability to use vi commands in jupyter would be very attractive for vi-type-editor users and could dramatically increase the power of  ipython/jupyter.

**Comment by Carreau** [comment]
Hum, you mean in the terminal ? The vi shortcuts are a feature of readline, you need to set it in your readline config that are terminal wide. You can aslo have a look at https://github.com/jonathanslenders/ptpython that provide a curse interface with emacs/vi keybinding.

**Comment by takluyver** [comment]
Alternatively, if you mean vim shortcuts in the notebook, look at [ipython-vimception](https://github.com/ivanov/ipython-vimception) - I think it might be broken with recent versions, but I'm sure it could be fixed up.

**Comment by jvtrudel** [comment]
Yeah, I mean vim shortcuts in the notebook. Thanks @takluyver , i'll have a look at it.

**Comment by Carreau** [comment]
Ok, closing. Also this would be more appropriate in Jupyter/notebook as a request. 
Be aware that the 3 level mode can be confusing at some points.
