### ISSUE TITLE
Config file option for confirm-exit/no-confirm-exit

### ISSUE THREAD

**Issue by jakirkham** [jupyter/jupyter_console#61]
Noticed that these options were listed under `jupyter console --help`. Would be nice if there was a way to set the default value for these in the config file. A simple boolean that serves both would work. If there already is a way to do this in the config file, it would be nice if that was added to this help string somehow (like what variable to set).

```
...
--confirm-exit
    Set to display confirmation dialog on exit. You can always use 'exit' or 'quit',
    to force a direct exit without any confirmation.
--no-confirm-exit
    Don't prompt the user when exiting. This will terminate the kernel
    if it is owned by the frontend, and leave it alive if it is external.
...
```

**Comment by takluyver** [comment]
```
c.TerminalInteractiveShell.confirm_exit
```

**Comment by jakirkham** [comment]
Cool, thanks @takluyver. I'll leave this open for the help string change. Though I did try to find where it was coming from and got kind of lost in a few repos.

**Comment by jakirkham** [comment]
NVM, it appears this has been done already. ( https://github.com/jupyter/jupyter_client/blob/bd9627d3f3bb656a583a69fd2b9bc19b3cd9e8f6/jupyter_client/consoleapp.py#L50 ). Not sure why it is still a problem then.

**Comment by jakirkham** [comment]
Ah, I understand now. I'll add a PR to fix it.

**Comment by jakirkham** [comment]
Added here ( https://github.com/jupyter/jupyter_client/pull/131 ). Please let me know what you think.
