### ISSUE TITLE
%pdb hangs the kernel

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_console#66]
Hi,

pretty easy to reproduce:

```
jupyter console
In [1]: x=10
In [2]: %pdb
Automatic pdb calling has been turned ON
In [3]: x.error()
```
hangs after [3].

Calling before or after doesnt make a difference.

**Comment by ocehugo** [comment]
Using --Session.debug=True avoid the problem.

**Comment by takluyver** [comment]
Curious. I've just tried this on master, and it works as expected whether I start it from the notebook or the console.

**Comment by ocehugo** [comment]
As always I report without testing further...my custom pager in ipython_config was causing this issue. vimpager is not working for jupyter console.

**Comment by takluyver** [comment]
I'm not sure why a pager would interfere with that - neither of them should be using the pager, as far as I can see. However, if vimpager is what it sounds like, it's probably something that should only be set for terminal IPython, not IPython running as a Jupyter kernel.

**Comment by ocehugo** [comment]
Just for the record : The problem disapears with c.TerminalInteractiveShell.pager = 'less'.
