### ISSUE TITLE
Install kernelspec on first `jupyter console`?

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter_console#7]
Installing just this repository (assume cloned)

```
pip install -r requirements.txt -e .
```

and trying to run

```
jupyter console
```

when you don't have any kernels ends up not being able to find the default kernel.

Should this install the kernelspec on first run?

If there's an issue that it would be installing a default, well `jupyter console` does launch the IPython kernel by default.

**Comment by takluyver** [comment]
Can you update jupyter_client? I think this should be fixed by #37.

**Comment by rgbkrk** [comment]
This was on a brand new person's laptop while I was at CodeConf, a JavaScript/Ruby dev who wanted to try out the sidecar.

**Comment by minrk** [comment]
I just tested this on a fresh docker machine, and installing this with `pip install --pre .` results in having the IPython kernel present.
