### ISSUE TITLE
%paste magic like ipython

### ISSUE THREAD

**Issue by bjoernh** [jupyter/jupyter_console#70]
It would be awesome if you could implement the %paste magic (like ipython console) for copy & paste big code blocks.

**Comment by Carreau** [comment]
you can use `cpaste`, `%past` cannot be implemented in the console as it is inherently a kernel side action and not a frontend one.

**Comment by takluyver** [comment]
We don't actually expose `%cpaste` from the kernel either.

However, jupyter_console 5.0 will be using prompt_toolkit, which can do multiline paste correctly, so as long as you have a terminal that supports bracketed paste, there should be no more need for %paste or %cpaste.

**Comment by takluyver** [comment]
Closing as you should now be able to paste directly into the interface.

**Comment by drcege** [comment]
@takluyver   I use Xshell and run  `jupyter console` in a remote server, however, I cannot do multiline paste. The version of Jupyter console is 5.1.0.

What is the reason, and why not  expose `%cpaste` in jupyter console and qtconsole ?
