### ISSUE TITLE
Release a beta

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter_console#82]
As the current version is incompatible with IPython 5.0 beta. .

**Comment by Carreau** [comment]
From the look of the changes, I'll propose to not do a 4.x and release a 5.0 Beta of this soonish. 
Any objection ?

**Comment by minrk** [comment]
Not at all. We should try to make sure this gets a 5.0 release before IPython.

**Comment by Carreau** [comment]
I'm going to do a beta1 of jupyter_console, and a beta2 of IPython in the next few hours. No reason to be cheap on beta. 

I'll upload to warehouse, and make a small announcement by replying the the beta1 thread. 

Ping @takluyver for info.

**Comment by Carreau** [comment]
b1 out, but not announced.
