### ISSUE TITLE
Document release process:

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter_console#83]
```
$ git clean -xfd
$ python setup.py sdist  --formats=gztar,zip
$ python setup.py bdist_wheel
$ twine upload dist/*
```

Need step to check pep440 version number consistency:

```
$ ls -1 dist
jupyter_console-5.0.0.dev.tar.gz
jupyter_console-5.0.0.dev.zip
jupyter_console-5.0.0.dev0-py2.py3-none-any.whl
```

Like pushing dev would be wrong as tar and wheel would appear as 2 different versions.

and `_version.py` is wrong:

```
version_info = (5, 0, 0, 'dev')
__version__ = '.'.join(map(str, version_info))
```
As beta and rc should not have dots separating patch versions from suffix.

**Comment by minrk** [comment]
Boy, I really dislike the effects of pep 440. If we imported setuptools on sdist, it would do the same normalization to both, and everything would be consistent. Similarly, it would probably be appropriate for twine to do normalization on upload, just as bdist_wheel does.

**Comment by Carreau** [comment]
> Boy, I really dislike the effects of pep 440.

Well but at least it normalize things. 
Really Python stdlib should ship with a Version object that have some logic to deal with that as well as comparisons.

**Comment by willingc** [comment]
@Carreau @minrk I will put together a doc for this similar to the one that I think we have for releasing notebook.

**Comment by Carreau** [comment]
And think the release process of this is slightly simpler. So we can have less complex docs.

**Comment by minrk** [comment]
@Carreau yes, it would be great if all the tools did pep440 normalizing. It's the partial implementation that bugs me - pip normalizes on install, so publishing packages with `.dev` is fine. We use setuptools for bdist_wheel, so normalization happens at packaging time, while sdist doesn't. If we consistently used or didn't use setuptools for dists, this wouldn't be an issue.
