### ISSUE TITLE
Add conda install instructions to README

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter_console#86]
The command to install on conda is:

```
conda install jupyter_console
```

Do we want to add this to the README?

Also, for what specific use cases do people use jupyter console? Command line interface to difference language kernels (i.e. iRkernel)

**Comment by Carreau** [comment]
> Also, for what specific use cases do people use jupyter console? Command line interface to difference language kernels (i.e. iRkernel)

Yes, or remote kernels, you can technically use jupyter_consoel to attach to a notebook kernel, or one on a remote machine. I guess.

**Comment by willingc** [comment]
Thanks @Carreau

**Comment by takluyver** [comment]
This is now in the README.
