### ISSUE TITLE
No lexer found in jupyter console

### ISSUE THREAD

**Issue by scopatz** [jupyter/jupyter_console#97]
As reported by @asmeurer in xonsh/xonsh#1440, the following will inescapably hang:

```
$jupyter console --kernel xonsh
/Users/aaronmeurer/anaconda3/envs/ipython5/lib/python3.5/site-packages/jupyter_console/ptshell.py:94: UserWarning: No lexer found for language 'xonsh'. Treating as plain text.
  warn("No lexer found for language %r. Treating as plain text." % name)
Jupyter console 5.0.0

Xonsh - the Python-ish, BASHwards-looking shell


In [1]:
```

It is not clear whose fault this is but the notebook with a xonsh kernel works just fine.  Thus I am reasonably sure that xonsh kernel hook is well-formed.  I can replicate this issue on my machine too.

**Comment by takluyver** [comment]
It's not hanging when I try it, with xonsh 0.4.3.

**Comment by scopatz** [comment]
So to be clear it only hangs for me when I type something and then hit enter.  Also, see this behaviour on both master and v0.4.3. Also:

```console
scopatz@localhost ~/xonsh master $ jupyter console --version
5.0.0
```

Thanks for looking into this @takluyver

**Comment by takluyver** [comment]
I was able to type stuff and execute it OK; I couldn't get output, seemingly xonsh sends [execute_result messages](http://jupyter-client.readthedocs.io/en/latest/messaging.html#id5) without the `execution_count` field, but that generated a traceback rather than a hang.

**Comment by scopatz** [comment]
Hmmm that seems strange since [all the messages seem to have execution count](https://github.com/xonsh/xonsh/blob/master/xonsh/jupyter_kernel.py#L79) which is implemented in [ipykernel itself](https://github.com/ipython/ipykernel/blob/master/ipykernel/kernelbase.py#L115).

**Comment by takluyver** [comment]
Those are `execute_reply` messages; the issue is with `execute_result`. Which doesn't actually seem to be generated in that code at all. I'll investigate some more.

**Comment by takluyver** [comment]
Aha, that's actually exposing a bug in ipykernel; I've just filed that as ipython/ipykernel#161.

**Comment by scopatz** [comment]
ahh I am glad it isn'

**Comment by takluyver** [comment]
I still don't know what was causing the hang you saw, though.

**Comment by scopatz** [comment]
closing based on closure of ipython/ipykernel#161

**Comment by scopatz** [comment]
Thanks again @takluyver!
