### ISSUE TITLE
Additional parts of substring when attempting code completion 

### ISSUE THREAD

**Issue by the-holger** [jupyter/jupyter_console#98]
Hi!

Not sure if this is the right repository for this issue, if not please accept my apologies.
After my latest package updates I've noticed a really strange behaviour for jupyter code completion. What's happening is that when starting to type e.g. a variable name or a package name and then using code completion, additional characters are inserted (i.e. parts of e.g. the file name are repeated) depending on previous tab completions. Steps to reproduce and screenshot below.

I'm running jupyter-console 5.0.0 on an Anaconda installation of Python 3.5.2 on Mac OS X (10.11.6).

Example:
1. ```>>> from pyramid.c <tab>``` completes to ```>>> from pyramid.co```, showing a dropdown with the two options "pyramid.compat" and "pyramid.config" 
2. Selecting either of them results in ```from pyramid.cod.compat or pyramid.cod.config```
3. ```>>> from pyramid.co <tab>``` opens the dropdown, the completion by selecting one of the options works though.

Same thing happens with variable names with underscores present:
1. ```>>> variable_name_one = 1```
2. ```>>> variable_name_two = 2```
3.  ```vari <tab>``` completes to ```variable_name_``` and opens the dropdown showing both names
4. Selecting either of them results in  ```variable_name_le_name_xxx```

When completing from a different position in the name:
5. ```varia <tab>``` completes to ```variable_name_``` and opens the dropdown showing both names
6. Selection either results in ```variable_name_able_name_xxx```
 
7. ```variable_name_ <tab>``` and selecting from the dropdown works though.

I'm absolutely clueless what might trigger that behaviour, so again: I'm sorry if jupyter-console is the wrong place to report that.

Cheers!
Holger

<img width="650" alt="screen shot 2016-08-09 at 19 28 12" src="https://cloud.githubusercontent.com/assets/1640406/17526437/8eed0742-5e67-11e6-9743-112803748205.png">

**Comment by takluyver** [comment]
That looks like a bug in prompt_toolkit. make sure you've got the latest version:

```shell
# If installed with pip:
pip install --upgrade prompt_toolkit
# If installed with conda:
conda update prompt_toolkit
```

**Comment by the-holger** [comment]
Thanks, I'll go ahead and open a issue there!
I made sure that I'm running the latest version of all packages before opening the issue here :-)

**Comment by takluyver** [comment]
Cross referencing for anyone interested in what happens: jonathanslenders/python-prompt-toolkit#370
